#!/usr/bin/env node
/**
 * DhakaFin token pipeline  —  DF-P1-003
 * ---------------------------------------------------------------
 * df.tokens.json  ──►  dist/tokens.css   (raw CSS custom properties + theme/tier overrides)
 *                 ──►  dist/theme.css    (Tailwind v4 @theme inline namespaces)
 *                 ──►  dist/base.css     (token-driven base element styles)
 *                 ──►  dist/tokens.ts    (typed constants for TS / Three.js / charts)
 *                 ──►  dist/tokens.json  (flattened map for tooling & debugging)
 *
 * Zero dependencies on purpose: the design system must never be able to fail
 * because a transitive npm package broke.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = join(HERE, 'dist');
const SRC = join(HERE, 'df.tokens.json');

const raw = JSON.parse(readFileSync(SRC, 'utf8'));

/* ───────────────────────── helpers ───────────────────────── */

const kebab = (s) =>
  String(s)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();

/** Walk the token tree, yielding { path, name(), value, node, group, parent } */
function walk(node, path = [], out = []) {
  if (node && typeof node === 'object' && 'value' in node && typeof node.value !== 'object') {
    out.push({ path, node });
    return out;
  }
  if (node && typeof node === 'object') {
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$')) continue;
      walk(child, [...path, key], out);
    }
  }
  return out;
}

const flat = walk(raw);
const isMetaGroup = (g) => ['$meta', 'contrastContract', 'motion', 'tier', 'a11y', 'format'].includes(g);

const isColorValue = (v) => typeof v === 'string' && (/^#|^rgba?\(|^linear-gradient|^radial-gradient/.test(v));

/* ─────────────────────── 1. tokens.css ─────────────────────── */

const cssVarName = (path) => `--df-${path.map(kebab).join('-')}`;

function declarations(list, { indent = '  ' } = {}) {
  return list
    .map(({ path, node }) => `${indent}${cssVarName(path)}: ${node.value};`)
    .join('\n');
}

// Groups that belong to the "theme layer" get emitted into :root; the rest are structural.
const themeNullable = ['color', 'gradient', 'border', 'scrim', 'glowSea', 'surfaceTint', 'surfaceTintStrong'];

const rootTokens = flat.filter(({ path }) => !isMetaGroup(path[0]));

const lightOverrides = Object.entries(raw.theme?.light ?? {});
const lightDecls = lightOverrides
  .map(([key, node]) => {
    // Light theme keys are either top-level colour names (void, surface1) or sea*
    const target = raw.color[key]
      ? `--df-color-${kebab(key)}`
      : // sea500 → --df-color-sea-500 ; buttonPrimaryBg → --df-color-button-primary-bg
        `--df-color-${kebab(key)}`;
    return `  ${target}: ${node.value};`;
  })
  .join('\n');

const tierDecls = Object.entries(raw.tier ?? {})
  .filter(([k]) => !k.startsWith('$'))
  .map(([tier, map]) => {
    const scale = map.durationScale ?? '1';
    return `[data-tier='${tier}'] {\n  --df-tier-duration-scale: ${scale};\n  --df-tier-blur: ${map.blur};\n  --df-tier-webgl: ${map.webgl};\n  --df-tier-spotlight: ${map.spotlight === 'on' ? '1' : '0'};\n  --df-tier-pinned-scroll: ${map.pinnedScroll === 'on' ? '1' : '0'};\n}`;
  })
  .join('\n\n');

const tokensCss = `/* ─────────────────────────────────────────────────────────────
 * AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT.
 * Source: packages/tokens/df.tokens.json
 * DhakaFin design tokens v${raw.$meta.version} · ${raw.$meta.phase}
 * ───────────────────────────────────────────────────────────── */

:root {
  /* Theme identity */
  --df-theme: dark;

${declarations(rootTokens, { indent: '  ' })}

  /* Default experience tier (overridden at runtime by [data-tier]) */
  --df-tier-duration-scale: 1;
  --df-tier-blur: ${raw.blur.glass.value};
  --df-tier-webgl: full;
  --df-tier-spotlight: 1;
  --df-tier-pinned-scroll: 1;

  /* Convenience aliases used by component classes */
  --df-duration-fast: calc(${raw.duration['1'].value} * var(--df-tier-duration-scale));
  --df-duration-base: calc(${raw.duration['2'].value} * var(--df-tier-duration-scale));
  --df-duration-slow: calc(${raw.duration['3'].value} * var(--df-tier-duration-scale));
  --df-duration-reveal: calc(${raw.duration['4'].value} * var(--df-tier-duration-scale));
  --df-duration-story: calc(${raw.duration['5'].value} * var(--df-tier-duration-scale));
}

/* ─── Light theme (secondary: printed reports, PDF exports, explicit user choice) ─── */
[data-theme='light'] {
  --df-theme: light;
${lightDecls}
}

/* ─── Experience tiers (blueprint §3.9) ─── */
${tierDecls}

/* ─── Reduced motion contract: all motion collapses to near-instant ─── */
@media (prefers-reduced-motion: reduce) {
  :root {
    --df-tier-duration-scale: 0.01;
    --df-tier-webgl: none;
    --df-tier-spotlight: 0;
    --df-tier-pinned-scroll: 0;
  }
}
`;

/* ─────────────────────── 2. theme.css (Tailwind v4) ─────────────────────── */

const ns = {
  color: 'color',
  font: 'font',
  fontSize: 'text',
  radius: 'radius',
  elevation: 'shadow',
  blur: 'blur',
  ease: 'ease',
  breakpoint: 'breakpoint',
  container: null, // not a Tailwind namespace — used via component classes
  duration: null,
  space: null, // handled explicitly below (base --spacing)
};

const themeLines = [];

// Colours → --color-<name>, referencing raw vars so runtime theming works.
const colorTokens = flat.filter(({ path }) => path[0] === 'color');
themeLines.push('  /* Colours */');
for (const { path } of colorTokens) {
  const name = path.slice(1).map(kebab).join('-');
  themeLines.push(`  --color-${name}: var(${cssVarName(path)});`);
}

// Colour utility aliases.
// Tailwind v4 keeps every colour token in one flat --color-* namespace, so a
// token already named after a CSS property (borderQuiet, textStrong) would emit
// a doubled utility: `border-border-quiet`. The alias map in the token file
// gives those tokens natural utility names without introducing a second value.
const colorAlias = raw.color?.$utilityAlias ?? {};
for (const [alias, target] of Object.entries(colorAlias)) {
  if (alias.startsWith('$')) continue;
  const source = colorTokens.find(({ path }) => path[1] === target);
  if (!source) {
    throw new Error(
      `df.tokens.json: color.$utilityAlias."${alias}" points at "${target}", which is not a colour token.`
    );
  }
  themeLines.push(`  --color-${kebab(alias)}: var(${cssVarName(source.path)});`);
}

// Fonts
themeLines.push('', '  /* Typography families */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'font' && path[1] !== 'budgetKB')) {
  themeLines.push(`  --font-${kebab(path[1])}: ${node.value};`);
}

// Type scale (size + line-height + letter-spacing + weight)
themeLines.push('', '  /* Type scale */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'fontSize')) {
  const name = kebab(path[1]);
  themeLines.push(`  --text-${name}: ${node.value};`);
  if (node.lineHeight) themeLines.push(`  --text-${name}--line-height: ${node.lineHeight};`);
  if (node.letterSpacing) themeLines.push(`  --text-${name}--letter-spacing: ${node.letterSpacing};`);
  if (node.fontWeight) themeLines.push(`  --text-${name}--font-weight: ${node.fontWeight};`);
}

// Spacing — base unit 4px so Tailwind's numeric scale matches the DF scale exactly.
themeLines.push(
  '',
  '  /* Spacing — base unit 4px: p-1=4px, p-2=8px, p-3=12px, p-4=16px, p-6=24px, p-8=32px, p-12=48px */',
  `  --spacing: ${raw.space['1'].value};`
);
for (const { path, node } of flat.filter(({ path }) => path[0] === 'space')) {
  themeLines.push(`  --spacing-${kebab(path[1])}: ${node.value};`);
}

// Radius
themeLines.push('', '  /* Radius */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'radius')) {
  themeLines.push(`  --radius-${kebab(path[1])}: ${node.value};`);
}

// Shadows
themeLines.push('', '  /* Elevation */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'elevation')) {
  themeLines.push(`  --shadow-${kebab(path[1])}: ${node.value};`);
}

// Blur
themeLines.push('', '  /* Blur */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'blur')) {
  themeLines.push(`  --blur-${kebab(path[1])}: var(--df-tier-blur, ${node.value});`);
}

// Easing
themeLines.push('', '  /* Motion easing */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'ease')) {
  themeLines.push(`  --ease-${kebab(path[1])}: ${node.value};`);
}

// Breakpoints
themeLines.push('', '  /* Breakpoints */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'breakpoint')) {
  themeLines.push(`  --breakpoint-${kebab(path[1])}: ${node.value};`);
}

// Containers (as max-width utilities: max-w-content / max-w-wide / max-w-reading)
themeLines.push('', '  /* Containers (max-w-content, max-w-wide, max-w-reading) */');
for (const { path, node } of flat.filter(({ path }) => path[0] === 'container')) {
  themeLines.push(`  --container-${kebab(path[1])}: ${node.value};`);
}

// Animations derived from signature motions
themeLines.push(
  '',
  '  /* Signature motion keyframes (see base.css for the implementations) */',
  '  --animate-df-stream: df-stream 2.4s linear infinite;',
  '  --animate-df-pulse: df-pulse-once 900ms var(--ease-out) 1;',
  '  --animate-df-shimmer: df-shimmer 1.6s linear infinite;'
);

const themeCss = `/* ─────────────────────────────────────────────────────────────
 * AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT.
 * Tailwind v4 theme layer. Uses \`@theme inline\` so that utilities
 * resolve to the raw --df-* variables and therefore follow runtime
 * theme ([data-theme]) and tier ([data-tier]) switches.
 * ───────────────────────────────────────────────────────────── */

@theme inline {
${themeLines.join('\n')}
}
`;

/* ─────────────────────── 3. base.css ─────────────────────── */

const baseCss = `/* ─────────────────────────────────────────────────────────────
 * AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT.
 * Token-driven base element styles, focus policy, motion primitives.
 * ───────────────────────────────────────────────────────────── */

@layer base {
  *,
  *::before,
  *::after {
    box-sizing: border-box;
  }

  html {
    -webkit-text-size-adjust: 100%;
    scroll-behavior: smooth;
    background-color: var(--df-color-void);
    color-scheme: dark;
  }

  [data-theme='light'] html,
  html[data-theme='light'] {
    color-scheme: light;
  }

  @media (prefers-reduced-motion: reduce) {
    html {
      scroll-behavior: auto;
    }
  }

  body {
    margin: 0;
    background-color: var(--df-color-void);
    color: var(--df-color-text);
    font-family: var(--df-font-sans);
    font-size: var(--text-body, 1rem);
    line-height: 1.7;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
    min-height: 100dvh;
  }

  /* Financial figures always use tabular numerals */
  .df-num,
  [data-numeric] {
    font-family: var(--df-font-num);
    font-variant-numeric: tabular-nums;
    font-feature-settings: 'tnum' 1, 'ss01' 1;
  }

  h1, h2, h3, h4, h5, h6 {
    margin: 0;
    color: var(--df-color-text-strong);
    font-weight: 700;
    text-wrap: balance;
  }

  p {
    margin: 0;
    text-wrap: pretty;
  }

  a {
    color: var(--df-color-sea-400);
    text-decoration-color: color-mix(in srgb, var(--df-color-sea-400) 40%, transparent);
    text-underline-offset: 3px;
    transition: color var(--df-duration-fast) var(--ease-out),
                text-decoration-color var(--df-duration-fast) var(--ease-out);
  }

  a:hover {
    color: var(--df-color-sea-300);
    text-decoration-color: currentColor;
  }

  /* Single focus policy for the entire product */
  :focus-visible {
    outline: none;
    box-shadow: var(--df-focus-ring);
    border-radius: var(--radius-sm);
  }

  ::selection {
    background-color: color-mix(in srgb, var(--df-color-sea-500) 32%, transparent);
    color: var(--df-color-text-strong);
  }

  img, svg, video {
    max-width: 100%;
    height: auto;
    display: block;
  }

  /* Scrollbars — quiet, brand-tinted, never a default grey slab */
  * {
    scrollbar-width: thin;
    scrollbar-color: color-mix(in srgb, var(--df-color-sea-500) 35%, transparent) transparent;
  }

  *::-webkit-scrollbar {
    width: 10px;
    height: 10px;
  }

  *::-webkit-scrollbar-track {
    background: transparent;
  }

  *::-webkit-scrollbar-thumb {
    background-color: color-mix(in srgb, var(--df-color-sea-500) 32%, transparent);
    border-radius: var(--radius-full);
    border: 2px solid transparent;
    background-clip: content-box;
  }

  *::-webkit-scrollbar-thumb:hover {
    background-color: color-mix(in srgb, var(--df-color-sea-400) 55%, transparent);
    background-clip: content-box;
  }
}

/* ─── Signature motion primitives (blueprint §3.10) ─── */
@layer utilities {
  @keyframes df-stream {
    from { stroke-dashoffset: 240; }
    to   { stroke-dashoffset: 0; }
  }

  @keyframes df-pulse-once {
    0%   { box-shadow: 0 0 0 0 var(--df-color-glow-sea); }
    70%  { box-shadow: 0 0 0 12px transparent; }
    100% { box-shadow: 0 0 0 0 transparent; }
  }

  @keyframes df-shimmer {
    from { background-position: -160% 0; }
    to   { background-position: 260% 0; }
  }

  @keyframes df-rise {
    from { opacity: 0; transform: translate3d(0, 16px, 0); }
    to   { opacity: 1; transform: translate3d(0, 0, 0); }
  }

  @keyframes df-fade {
    from { opacity: 0; }
    to   { opacity: 1; }
  }

  @keyframes df-count-in {
    from { opacity: 0; transform: translate3d(0, 8px, 0); }
    to   { opacity: 1; transform: translate3d(0, 0, 0); }
  }

  /* Reveal-on-scroll: applied by <Reveal>; final state is always visible. */
  .df-reveal {
    opacity: 0;
  }

  .df-reveal[data-visible='true'] {
    animation: df-rise var(--df-duration-reveal) var(--ease-out) both;
  }

  /* Lite tier / reduced motion: content is simply present — never hidden. */
  [data-tier='lite'] .df-reveal,
  .df-reveal[data-motion='off'] {
    opacity: 1;
    animation: none;
  }

  /* Ledger row: draw-in accent line, like ink on a ledger */
  .df-ledger-row {
    position: relative;
  }

  .df-ledger-row::before {
    content: '';
    position: absolute;
    inset-inline-start: 0;
    top: 50%;
    height: 1px;
    width: 0;
    background: var(--df-gradient-sealine);
    transition: width var(--df-duration-reveal) var(--ease-out);
  }

  .df-ledger-row[data-visible='true']::before {
    width: 100%;
  }

  /* Data stream: animated dash along a path */
  .df-stream {
    stroke-dasharray: 6 12;
    animation: var(--animate-df-stream);
  }

  [data-tier='lite'] .df-stream,
  .df-stream[data-motion='off'] {
    animation: none;
    stroke-dasharray: none;
  }

  /* Metal edge: the detail that makes dark surfaces feel machined, not flat */
  .df-metal-edge {
    box-shadow: var(--df-elevation-inner), var(--df-elevation-2);
  }

  /* Hairline grid: the financial-ledger motif */
  .df-hairline-grid {
    background-image:
      linear-gradient(to right, var(--df-color-border-quiet) 1px, transparent 1px),
      linear-gradient(to bottom, var(--df-color-border-quiet) 1px, transparent 1px);
    background-size: 64px 64px;
  }

  /* Grain layer: kills banding in large dark gradients */
  .df-grain::after {
    content: '';
    position: absolute;
    inset: 0;
    pointer-events: none;
    opacity: 0.035;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='120' height='120' filter='url(%23n)'/%3E%3C/svg%3E");
  }

  [data-tier='lite'] .df-grain::after {
    display: none;
  }

  /* Spotlight: pointer-following radial highlight (ultra/high only) */
  .df-spotlight {
    position: relative;
    overflow: hidden;
  }

  .df-spotlight::after {
    content: '';
    position: absolute;
    inset: 0;
    pointer-events: none;
    opacity: 0;
    transition: opacity var(--df-duration-slow) var(--ease-out);
    background: radial-gradient(
      240px circle at var(--df-spot-x, 50%) var(--df-spot-y, 50%),
      color-mix(in srgb, var(--df-color-sea-400) 14%, transparent),
      transparent 70%
    );
  }

  .df-spotlight:hover::after,
  .df-spotlight:focus-within::after {
    opacity: 1;
  }

  [data-tier='lite'] .df-spotlight::after,
  [data-tier='balanced'] .df-spotlight::after {
    display: none;
  }

  /* Splash gradient used by hero/atmosphere layers */
  .df-atmosphere {
    background-image: var(--df-gradient-depth);
  }
}

/* ─── Reduced-motion contract: nothing animates, everything is visible ─── */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }

  .df-reveal {
    opacity: 1 !important;
  }
}
`;

/* ─────────────────────── 4. tokens.ts ─────────────────────── */

const tsEntries = flat
  .filter(({ path }) => !isMetaGroup(path[0]))
  .map(({ path, node }) => {
    const key = path.map((p) => (/^\d+$/.test(p) ? `'${p}'` : /^[a-zA-Z_$][\w$]*$/.test(p) ? p : `'${p}'`)).join('.');
    return `  '${path.join('.')}': ${JSON.stringify(String(node.value))},`;
  })
  .join('\n');

const lightTs = Object.entries(raw.theme?.light ?? {})
  .map(([k, v]) => `  '${k}': ${JSON.stringify(String(v.value))},`)
  .join('\n');

const tokensTs = `/* ─────────────────────────────────────────────────────────────
 * AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT.
 * Typed token constants for TypeScript, Three.js materials and chart config.
 * ───────────────────────────────────────────────────────────── */

export const tokens = {
${tsEntries}
} as const;

export type TokenPath = keyof typeof tokens;

/** Light-theme overrides (secondary theme: print/PDF/explicit user choice). */
export const lightThemeOverrides = {
${lightTs}
} as const;

/** CSS custom property name for a token path, e.g. cssVar('color.sea.500') -> "var(--df-color-sea-500)" */
export function cssVar(path: string): string {
  return 'var(' + cssVarName(path) + ')';
}

/** Raw custom property name (without var()). */
export function cssVarName(path: string): string {
  return (
    '--df-' +
    path
      .split('.')
      .map((segment) => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase())
      .join('-')
  );
}

export const meta = {
  version: ${JSON.stringify(raw.$meta.version)},
  phase: ${JSON.stringify(raw.$meta.phase)},
  standard: ${JSON.stringify(raw.a11y.standard.value)},
  defaultTheme: 'dark',
  tiers: ['ultra', 'high', 'balanced', 'lite'] as const,
} as const;

export type ExperienceTier = (typeof meta.tiers)[number];
`;

/* ─────────────────────── write ─────────────────────── */

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, 'tokens.css'), tokensCss);
writeFileSync(join(DIST, 'theme.css'), themeCss);
writeFileSync(join(DIST, 'base.css'), baseCss);
writeFileSync(join(DIST, 'tokens.ts'), tokensTs);
writeFileSync(join(DIST, 'tokens.json'), JSON.stringify(Object.fromEntries(flat.map(({ path, node }) => [path.join('.'), node.value])), null, 2) + '\n');

const groups = [...new Set(flat.filter(({ path }) => !isMetaGroup(path[0])).map(({ path }) => path[0]))];
console.log(`✓ tokens built → packages/tokens/dist/  (${flat.length} tokens across ${groups.length} groups)`);
console.log(`  groups: ${groups.join(', ')}`);
console.log(`  files: tokens.css · theme.css · base.css · tokens.ts · tokens.json`);
